services:
  postgres:
    image: postgres:16
    container_name: credito_postgres
    environment:
      POSTGRES_USER: credito
      POSTGRES_PASSWORD: credito
      POSTGRES_DB: credito_db
    ports:
      - "5432:5432"
    volumes:
      - credito_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credito -d credito_db -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: credito_redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health --api-urls localhost:9644"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 15s

  redpanda-init:
    image: redpandadata/redpanda:latest
    container_name: credito_redpanda_init
    depends_on:
        redpanda:
            condition: service_healthy
    entrypoint:
          - bash
          - -lc
          - |
            rpk topic create integrar-credito-constituido-entry -p 1 -r 1 --brokers redpanda:29092 || true
            rpk topic create credito-consulta-audit -p 1 -r 1 --brokers redpanda:29092 || true
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credito_api
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      redpanda-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=credito_db;Username=credito;Password=credito
      Kafka__BootstrapServers: redpanda:29092
      Kafka__IntegrationTopicName: integrar-credito-constituido-entry
      Kafka__AuditTopicName: credito-consulta-audit
      Kafka__ConsumerGroupId: credito-constituido-worker

volumes:
  credito_pgdata:
